///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AndroidKeePassSample
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AndroidKeePassSampleRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b2165425-9a13-456e-bd7f-39fff1070cf5")]
    public partial class AndroidKeePassSampleRepository : RepoGenBaseFolder
    {
        static AndroidKeePassSampleRepository instance = new AndroidKeePassSampleRepository();
        AndroidKeePassSampleRepositoryFolders.ComAndroidKeepassAppFolder _comandroidkeepass;
        RepoItemInfo _passwordinformation_shortsearchtimeoutInfo;
        RepoItemInfo _btok_shortsearchtimeoutInfo;

        /// <summary>
        /// Gets the singleton class instance representing the AndroidKeePassSampleRepository element repository.
        /// </summary>
        [RepositoryFolder("b2165425-9a13-456e-bd7f-39fff1070cf5")]
        public static AndroidKeePassSampleRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AndroidKeePassSampleRepository() 
            : base("AndroidKeePassSampleRepository", "/", null, 0, false, "b2165425-9a13-456e-bd7f-39fff1070cf5", ".\\RepositoryImages\\AndroidKeePassSampleRepositoryb2165425.rximgres")
        {
            _comandroidkeepass = new AndroidKeePassSampleRepositoryFolders.ComAndroidKeepassAppFolder(this);
            _passwordinformation_shortsearchtimeoutInfo = new RepoItemInfo(this, "PasswordInformation_ShortSearchTimeout", "/mobileapp[@title='com.android.keepass']/form[@title='PasswordActivity']//text[@resourceid='R.string.entry_and_or']", 30000, null, "6eb9476a-0827-407a-af72-1f31704e9a37");
            _btok_shortsearchtimeoutInfo = new RepoItemInfo(this, "btOK_ShortSearchTimeout", "/mobileapp[@title='com.android.keepass']//button[@rid='ok']", 30000, null, "b5d63a70-2614-45fc-b406-6349afc0e317");
        }

#region Variables

        string _varTitle = "WordPressDemo";

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("487240f8-860c-471c-8bee-8922c9e0acbc")]
        public string varTitle
        {
            get { return _varTitle; }
            set { _varTitle = value; }
        }

        string _varIconIndexRepo = "5";

        /// <summary>
        /// Gets or sets the value of variable varIconIndexRepo.
        /// </summary>
        [TestVariable("bb6715bb-f398-4464-b5bd-2861dffd62af")]
        public string varIconIndexRepo
        {
            get { return _varIconIndexRepo; }
            set { _varIconIndexRepo = value; }
        }

        string _varGroupName = "Ranorex";

        /// <summary>
        /// Gets or sets the value of variable varGroupName.
        /// </summary>
        [TestVariable("20304009-2a35-4050-9036-e53d51cc5590")]
        public string varGroupName
        {
            get { return _varGroupName; }
            set { _varGroupName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b2165425-9a13-456e-bd7f-39fff1070cf5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PasswordInformation_ShortSearchTimeout item.
        /// </summary>
        [RepositoryItem("6eb9476a-0827-407a-af72-1f31704e9a37")]
        public virtual Ranorex.Text PasswordInformation_ShortSearchTimeout
        {
            get
            {
                 return _passwordinformation_shortsearchtimeoutInfo.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The PasswordInformation_ShortSearchTimeout item info.
        /// </summary>
        [RepositoryItemInfo("6eb9476a-0827-407a-af72-1f31704e9a37")]
        public virtual RepoItemInfo PasswordInformation_ShortSearchTimeoutInfo
        {
            get
            {
                return _passwordinformation_shortsearchtimeoutInfo;
            }
        }

        /// <summary>
        /// The btOK_ShortSearchTimeout item.
        /// </summary>
        [RepositoryItem("b5d63a70-2614-45fc-b406-6349afc0e317")]
        public virtual Ranorex.Button btOK_ShortSearchTimeout
        {
            get
            {
                 return _btok_shortsearchtimeoutInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The btOK_ShortSearchTimeout item info.
        /// </summary>
        [RepositoryItemInfo("b5d63a70-2614-45fc-b406-6349afc0e317")]
        public virtual RepoItemInfo btOK_ShortSearchTimeoutInfo
        {
            get
            {
                return _btok_shortsearchtimeoutInfo;
            }
        }

        /// <summary>
        /// The ComAndroidKeepass folder.
        /// </summary>
        [RepositoryFolder("c00377a1-b507-499c-9886-5e7f4c91803d")]
        public virtual AndroidKeePassSampleRepositoryFolders.ComAndroidKeepassAppFolder ComAndroidKeepass
        {
            get { return _comandroidkeepass; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AndroidKeePassSampleRepositoryFolders
    {
        /// <summary>
        /// The ComAndroidKeepassAppFolder folder.
        /// </summary>
        [RepositoryFolder("c00377a1-b507-499c-9886-5e7f4c91803d")]
        public partial class ComAndroidKeepassAppFolder : RepoGenBaseFolder
        {
            AndroidKeePassSampleRepositoryFolders.CreateDatabaseFolder _createdatabase;
            AndroidKeePassSampleRepositoryFolders.EntryActivityFolder _entryactivity;
            AndroidKeePassSampleRepositoryFolders.FileSelectFolder _fileselect;
            AndroidKeePassSampleRepositoryFolders.PasswordActivityFolder _passwordactivity;
            AndroidKeePassSampleRepositoryFolders.GroupActivityFolder _groupactivity;
            RepoItemInfo _groupnameInfo;
            RepoItemInfo _deletegroupInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _iconimageInfo;

            /// <summary>
            /// Creates a new ComAndroidKeepass  folder.
            /// </summary>
            public ComAndroidKeepassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComAndroidKeepass", "/mobileapp[@title='com.android.keepass']", parentFolder, 30000, null, false, "c00377a1-b507-499c-9886-5e7f4c91803d", "")
            {
                _createdatabase = new AndroidKeePassSampleRepositoryFolders.CreateDatabaseFolder(this);
                _entryactivity = new AndroidKeePassSampleRepositoryFolders.EntryActivityFolder(this);
                _fileselect = new AndroidKeePassSampleRepositoryFolders.FileSelectFolder(this);
                _passwordactivity = new AndroidKeePassSampleRepositoryFolders.PasswordActivityFolder(this);
                _groupactivity = new AndroidKeePassSampleRepositoryFolders.GroupActivityFolder(this);
                _groupnameInfo = new RepoItemInfo(this, "GroupName", ".//text[@rid='group_name']", "", 30000, null, "1535fdc8-db09-4b6f-922c-f6f14cca48b2");
                _deletegroupInfo = new RepoItemInfo(this, "DeleteGroup", ".//container[@containertype='Relative']/text[@resourceid='R.string.menu_delete']", "", 30000, null, "562c4c9e-4a34-45a7-9fcf-5c2f7da83573");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//container[@containertype='Relative']/text[@resourceid='R.string.menu_delete']", "", 30000, null, "fa08fbc4-83a1-4125-99a4-44579418dd2e");
                _iconimageInfo = new RepoItemInfo(this, "IconImage", "form[@title='IconPickerActivity']/?/?/?/container[$variconindexrepo]/picture[@rid='icon_image']", "", 30000, null, "b7932dcd-789f-4894-b5b4-d7b9b4dd102c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c00377a1-b507-499c-9886-5e7f4c91803d")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c00377a1-b507-499c-9886-5e7f4c91803d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GroupName item.
            /// </summary>
            [RepositoryItem("1535fdc8-db09-4b6f-922c-f6f14cca48b2")]
            public virtual Ranorex.Text GroupName
            {
                get
                {
                    return _groupnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroupName item info.
            /// </summary>
            [RepositoryItemInfo("1535fdc8-db09-4b6f-922c-f6f14cca48b2")]
            public virtual RepoItemInfo GroupNameInfo
            {
                get
                {
                    return _groupnameInfo;
                }
            }

            /// <summary>
            /// The DeleteGroup item.
            /// </summary>
            [RepositoryItem("562c4c9e-4a34-45a7-9fcf-5c2f7da83573")]
            public virtual Ranorex.Text DeleteGroup
            {
                get
                {
                    return _deletegroupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DeleteGroup item info.
            /// </summary>
            [RepositoryItemInfo("562c4c9e-4a34-45a7-9fcf-5c2f7da83573")]
            public virtual RepoItemInfo DeleteGroupInfo
            {
                get
                {
                    return _deletegroupInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("fa08fbc4-83a1-4125-99a4-44579418dd2e")]
            public virtual Ranorex.Text Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("fa08fbc4-83a1-4125-99a4-44579418dd2e")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The IconImage item.
            /// </summary>
            [RepositoryItem("b7932dcd-789f-4894-b5b4-d7b9b4dd102c")]
            public virtual Ranorex.Picture IconImage
            {
                get
                {
                    return _iconimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The IconImage item info.
            /// </summary>
            [RepositoryItemInfo("b7932dcd-789f-4894-b5b4-d7b9b4dd102c")]
            public virtual RepoItemInfo IconImageInfo
            {
                get
                {
                    return _iconimageInfo;
                }
            }

            /// <summary>
            /// The CreateDatabase folder.
            /// </summary>
            [RepositoryFolder("309cb7c8-91da-4cdb-83e1-1e3466b59507")]
            public virtual AndroidKeePassSampleRepositoryFolders.CreateDatabaseFolder CreateDatabase
            {
                get { return _createdatabase; }
            }

            /// <summary>
            /// The EntryActivity folder.
            /// </summary>
            [RepositoryFolder("549014ac-35d0-482f-902c-1026e46c912e")]
            public virtual AndroidKeePassSampleRepositoryFolders.EntryActivityFolder EntryActivity
            {
                get { return _entryactivity; }
            }

            /// <summary>
            /// The FileSelect folder.
            /// </summary>
            [RepositoryFolder("f3c1d9f2-374a-4483-904c-f89152b75563")]
            public virtual AndroidKeePassSampleRepositoryFolders.FileSelectFolder FileSelect
            {
                get { return _fileselect; }
            }

            /// <summary>
            /// The PasswordActivity folder.
            /// </summary>
            [RepositoryFolder("d168e284-e0e2-4c06-83dd-839eba2d2098")]
            public virtual AndroidKeePassSampleRepositoryFolders.PasswordActivityFolder PasswordActivity
            {
                get { return _passwordactivity; }
            }

            /// <summary>
            /// The GroupActivity folder.
            /// </summary>
            [RepositoryFolder("8afd07a7-12f1-4612-a743-b5b159ea3acd")]
            public virtual AndroidKeePassSampleRepositoryFolders.GroupActivityFolder GroupActivity
            {
                get { return _groupactivity; }
            }
        }

        /// <summary>
        /// The CreateDatabaseFolder folder.
        /// </summary>
        [RepositoryFolder("309cb7c8-91da-4cdb-83e1-1e3466b59507")]
        public partial class CreateDatabaseFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passconfpasswordInfo;
            RepoItemInfo _passpasswordInfo;

            /// <summary>
            /// Creates a new CreateDatabase  folder.
            /// </summary>
            public CreateDatabaseFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateDatabase", "form[@title='(none)']", parentFolder, 30000, null, false, "309cb7c8-91da-4cdb-83e1-1e3466b59507", "")
            {
                _passconfpasswordInfo = new RepoItemInfo(this, "PassConfPassword", ".//text[@rid='pass_conf_password']", "", 30000, null, "297e4a18-ab39-4d19-82fc-c3c430e94233");
                _passpasswordInfo = new RepoItemInfo(this, "PassPassword", ".//text[@rid='pass_password']", "", 30000, null, "4f44a67b-d666-44e2-8c9e-1cd6226c57a7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("309cb7c8-91da-4cdb-83e1-1e3466b59507")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("309cb7c8-91da-4cdb-83e1-1e3466b59507")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PassConfPassword item.
            /// </summary>
            [RepositoryItem("297e4a18-ab39-4d19-82fc-c3c430e94233")]
            public virtual Ranorex.Text PassConfPassword
            {
                get
                {
                    return _passconfpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PassConfPassword item info.
            /// </summary>
            [RepositoryItemInfo("297e4a18-ab39-4d19-82fc-c3c430e94233")]
            public virtual RepoItemInfo PassConfPasswordInfo
            {
                get
                {
                    return _passconfpasswordInfo;
                }
            }

            /// <summary>
            /// The PassPassword item.
            /// </summary>
            [RepositoryItem("4f44a67b-d666-44e2-8c9e-1cd6226c57a7")]
            public virtual Ranorex.Text PassPassword
            {
                get
                {
                    return _passpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PassPassword item info.
            /// </summary>
            [RepositoryItemInfo("4f44a67b-d666-44e2-8c9e-1cd6226c57a7")]
            public virtual RepoItemInfo PassPasswordInfo
            {
                get
                {
                    return _passpasswordInfo;
                }
            }
        }

        /// <summary>
        /// The EntryActivityFolder folder.
        /// </summary>
        [RepositoryFolder("549014ac-35d0-482f-902c-1026e46c912e")]
        public partial class EntryActivityFolder : RepoGenBaseFolder
        {
            AndroidKeePassSampleRepositoryFolders.TextFieldsFolder _textfields;
            RepoItemInfo _saveInfo;
            RepoItemInfo _iconbuttonInfo;

            /// <summary>
            /// Creates a new EntryActivity  folder.
            /// </summary>
            public EntryActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("EntryActivity", "form[@title>'EntryEditActivity']/container/container", parentFolder, 30000, null, false, "549014ac-35d0-482f-902c-1026e46c912e", "")
            {
                _textfields = new AndroidKeePassSampleRepositoryFolders.TextFieldsFolder(this);
                _saveInfo = new RepoItemInfo(this, "Save", "button[@resourceid='R.string.entry_save']", "", 30000, null, "3972fa74-553d-40db-8234-ec66bdb41628");
                _iconbuttonInfo = new RepoItemInfo(this, "IconButton", "*/container/button[@rid='icon_button']", "", 30000, null, "8cae0a53-85e8-4074-ad62-5307c9cc22b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("549014ac-35d0-482f-902c-1026e46c912e")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("549014ac-35d0-482f-902c-1026e46c912e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("3972fa74-553d-40db-8234-ec66bdb41628")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("3972fa74-553d-40db-8234-ec66bdb41628")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The IconButton item.
            /// </summary>
            [RepositoryItem("8cae0a53-85e8-4074-ad62-5307c9cc22b6")]
            public virtual Ranorex.Button IconButton
            {
                get
                {
                    return _iconbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The IconButton item info.
            /// </summary>
            [RepositoryItemInfo("8cae0a53-85e8-4074-ad62-5307c9cc22b6")]
            public virtual RepoItemInfo IconButtonInfo
            {
                get
                {
                    return _iconbuttonInfo;
                }
            }

            /// <summary>
            /// The TextFields folder.
            /// </summary>
            [RepositoryFolder("18dbd3a3-97c8-485c-abdd-9166d3819dbc")]
            public virtual AndroidKeePassSampleRepositoryFolders.TextFieldsFolder TextFields
            {
                get { return _textfields; }
            }
        }

        /// <summary>
        /// The TextFieldsFolder folder.
        /// </summary>
        [RepositoryFolder("18dbd3a3-97c8-485c-abdd-9166d3819dbc")]
        public partial class TextFieldsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _entryconfpasswordInfo;
            RepoItemInfo _entrypasswordInfo;
            RepoItemInfo _entrytitleInfo;
            RepoItemInfo _entryurlInfo;
            RepoItemInfo _entryusernameInfo;

            /// <summary>
            /// Creates a new TextFields  folder.
            /// </summary>
            public TextFieldsFolder(RepoGenBaseFolder parentFolder) :
                    base("TextFields", "*/container", parentFolder, 30000, null, false, "18dbd3a3-97c8-485c-abdd-9166d3819dbc", "")
            {
                _entryconfpasswordInfo = new RepoItemInfo(this, "EntryConfpassword", "text[@rid='entry_confpassword']", "", 30000, null, "0e853dcb-82d4-40d5-ab4d-99ca415593b7");
                _entrypasswordInfo = new RepoItemInfo(this, "EntryPassword", "text[@rid='entry_password']", "", 30000, null, "e2c0c51a-98e3-460a-8d12-bb1b9d483278");
                _entrytitleInfo = new RepoItemInfo(this, "EntryTitle", "text[@rid='entry_title']", "", 30000, null, "02d2e063-5fb0-4540-b497-9948c4916def");
                _entryurlInfo = new RepoItemInfo(this, "EntryUrl", "text[@rid='entry_url']", "", 30000, null, "3265581a-ade9-4afa-a2d3-66564333f976");
                _entryusernameInfo = new RepoItemInfo(this, "EntryUserName", "text[@rid='entry_user_name']", "", 30000, null, "b2ab7bd3-3b1b-4812-ada4-720892290382");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("18dbd3a3-97c8-485c-abdd-9166d3819dbc")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("18dbd3a3-97c8-485c-abdd-9166d3819dbc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EntryConfpassword item.
            /// </summary>
            [RepositoryItem("0e853dcb-82d4-40d5-ab4d-99ca415593b7")]
            public virtual Ranorex.Text EntryConfpassword
            {
                get
                {
                    return _entryconfpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryConfpassword item info.
            /// </summary>
            [RepositoryItemInfo("0e853dcb-82d4-40d5-ab4d-99ca415593b7")]
            public virtual RepoItemInfo EntryConfpasswordInfo
            {
                get
                {
                    return _entryconfpasswordInfo;
                }
            }

            /// <summary>
            /// The EntryPassword item.
            /// </summary>
            [RepositoryItem("e2c0c51a-98e3-460a-8d12-bb1b9d483278")]
            public virtual Ranorex.Text EntryPassword
            {
                get
                {
                    return _entrypasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryPassword item info.
            /// </summary>
            [RepositoryItemInfo("e2c0c51a-98e3-460a-8d12-bb1b9d483278")]
            public virtual RepoItemInfo EntryPasswordInfo
            {
                get
                {
                    return _entrypasswordInfo;
                }
            }

            /// <summary>
            /// The EntryTitle item.
            /// </summary>
            [RepositoryItem("02d2e063-5fb0-4540-b497-9948c4916def")]
            public virtual Ranorex.Text EntryTitle
            {
                get
                {
                    return _entrytitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryTitle item info.
            /// </summary>
            [RepositoryItemInfo("02d2e063-5fb0-4540-b497-9948c4916def")]
            public virtual RepoItemInfo EntryTitleInfo
            {
                get
                {
                    return _entrytitleInfo;
                }
            }

            /// <summary>
            /// The EntryUrl item.
            /// </summary>
            [RepositoryItem("3265581a-ade9-4afa-a2d3-66564333f976")]
            public virtual Ranorex.Text EntryUrl
            {
                get
                {
                    return _entryurlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryUrl item info.
            /// </summary>
            [RepositoryItemInfo("3265581a-ade9-4afa-a2d3-66564333f976")]
            public virtual RepoItemInfo EntryUrlInfo
            {
                get
                {
                    return _entryurlInfo;
                }
            }

            /// <summary>
            /// The EntryUserName item.
            /// </summary>
            [RepositoryItem("b2ab7bd3-3b1b-4812-ada4-720892290382")]
            public virtual Ranorex.Text EntryUserName
            {
                get
                {
                    return _entryusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryUserName item info.
            /// </summary>
            [RepositoryItemInfo("b2ab7bd3-3b1b-4812-ada4-720892290382")]
            public virtual RepoItemInfo EntryUserNameInfo
            {
                get
                {
                    return _entryusernameInfo;
                }
            }
        }

        /// <summary>
        /// The FileSelectFolder folder.
        /// </summary>
        [RepositoryFolder("f3c1d9f2-374a-4483-904c-f89152b75563")]
        public partial class FileSelectFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createdatabaseInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _databasefilenameInfo;

            /// <summary>
            /// Creates a new FileSelect  folder.
            /// </summary>
            public FileSelectFolder(RepoGenBaseFolder parentFolder) :
                    base("FileSelect", "form[@title='FileSelectActivity']/container/container/androidelement[@rid='file_select']/container", parentFolder, 30000, null, false, "f3c1d9f2-374a-4483-904c-f89152b75563", "")
            {
                _createdatabaseInfo = new RepoItemInfo(this, "CreateDatabase", "button[@resourceid='R.string.menu_create']", "", 30000, null, "2feb19e4-84ae-41a4-8eb1-0545bf0f365a");
                _openInfo = new RepoItemInfo(this, "Open", "button[@resourceid='R.string.menu_open']", "", 30000, null, "3e8ab729-8f87-46c8-b14a-c5e282e1ea84");
                _databasefilenameInfo = new RepoItemInfo(this, "DatabaseFilename", "text[@rid='file_filename']", "", 30000, null, "0a20615c-bfc0-4768-bf01-90231b44b1bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f3c1d9f2-374a-4483-904c-f89152b75563")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f3c1d9f2-374a-4483-904c-f89152b75563")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateDatabase item.
            /// </summary>
            [RepositoryItem("2feb19e4-84ae-41a4-8eb1-0545bf0f365a")]
            public virtual Ranorex.Button CreateDatabase
            {
                get
                {
                    return _createdatabaseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateDatabase item info.
            /// </summary>
            [RepositoryItemInfo("2feb19e4-84ae-41a4-8eb1-0545bf0f365a")]
            public virtual RepoItemInfo CreateDatabaseInfo
            {
                get
                {
                    return _createdatabaseInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("3e8ab729-8f87-46c8-b14a-c5e282e1ea84")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("3e8ab729-8f87-46c8-b14a-c5e282e1ea84")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The DatabaseFilename item.
            /// </summary>
            [RepositoryItem("0a20615c-bfc0-4768-bf01-90231b44b1bc")]
            public virtual Ranorex.Text DatabaseFilename
            {
                get
                {
                    return _databasefilenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DatabaseFilename item info.
            /// </summary>
            [RepositoryItemInfo("0a20615c-bfc0-4768-bf01-90231b44b1bc")]
            public virtual RepoItemInfo DatabaseFilenameInfo
            {
                get
                {
                    return _databasefilenameInfo;
                }
            }
        }

        /// <summary>
        /// The PasswordActivityFolder folder.
        /// </summary>
        [RepositoryFolder("d168e284-e0e2-4c06-83dd-839eba2d2098")]
        public partial class PasswordActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new PasswordActivity  folder.
            /// </summary>
            public PasswordActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("PasswordActivity", "form[@title='PasswordActivity']/container/container", parentFolder, 30000, null, false, "d168e284-e0e2-4c06-83dd-839eba2d2098", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", "text[@rid='password']", "", 30000, null, "2e1fb144-1542-45f2-b887-ed2365bfcbdc");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@resourceid~'R.string']", "", 30000, null, "51941f3a-2765-47c5-b755-bb44ea757f70");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d168e284-e0e2-4c06-83dd-839eba2d2098")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d168e284-e0e2-4c06-83dd-839eba2d2098")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("2e1fb144-1542-45f2-b887-ed2365bfcbdc")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("2e1fb144-1542-45f2-b887-ed2365bfcbdc")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("51941f3a-2765-47c5-b755-bb44ea757f70")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("51941f3a-2765-47c5-b755-bb44ea757f70")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The GroupActivityFolder folder.
        /// </summary>
        [RepositoryFolder("8afd07a7-12f1-4612-a743-b5b159ea3acd")]
        public partial class GroupActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _internetInfo;
            RepoItemInfo _addentryInfo;
            RepoItemInfo _demodriventitleInfo;
            RepoItemInfo _groupactivityv3Info;
            RepoItemInfo _addgroupInfo;
            RepoItemInfo _groupentryInfo;

            /// <summary>
            /// Creates a new GroupActivity  folder.
            /// </summary>
            public GroupActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("GroupActivity", "form[@title='GroupActivityV3']", parentFolder, 30000, null, false, "8afd07a7-12f1-4612-a743-b5b159ea3acd", "")
            {
                _internetInfo = new RepoItemInfo(this, "Internet", "container/androidelement/container/list/androidelement/table/row/text[@caption='Internet']", "", 30000, null, "ef7d31e5-41cc-4297-9458-b692e8ea8d4b");
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "container/androidelement/container/button[@resourceid='R.string.add_entry']", "", 30000, null, "ce373854-8e5a-4a4f-ad49-5adac2e7c60f");
                _demodriventitleInfo = new RepoItemInfo(this, "DemoDrivenTitle", "container/androidelement/container/list/androidelement/table/row/text[@caption=$vartitle]", "", 30000, null, "8933de81-7251-45fc-ab99-c985b2ecf3b3");
                _groupactivityv3Info = new RepoItemInfo(this, "GroupActivityV3", "", "", 30000, null, "94eb7b91-1abe-43a2-bd03-14066965967c");
                _addgroupInfo = new RepoItemInfo(this, "AddGroup", "container/androidelement/container/button[@rid='add_group']", "", 30000, null, "215f1f0f-a7cd-409f-b4f0-f3d3caa20554");
                _groupentryInfo = new RepoItemInfo(this, "GroupEntry", "container/androidelement/container/list/androidelement/table/row/text[@caption=$vargroupname]", "", 30000, null, "6631966a-ee17-4f57-869c-7292393020ca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8afd07a7-12f1-4612-a743-b5b159ea3acd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8afd07a7-12f1-4612-a743-b5b159ea3acd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Internet item.
            /// </summary>
            [RepositoryItem("ef7d31e5-41cc-4297-9458-b692e8ea8d4b")]
            public virtual Ranorex.Text Internet
            {
                get
                {
                    return _internetInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Internet item info.
            /// </summary>
            [RepositoryItemInfo("ef7d31e5-41cc-4297-9458-b692e8ea8d4b")]
            public virtual RepoItemInfo InternetInfo
            {
                get
                {
                    return _internetInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("ce373854-8e5a-4a4f-ad49-5adac2e7c60f")]
            public virtual Ranorex.Button AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("ce373854-8e5a-4a4f-ad49-5adac2e7c60f")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The DemoDrivenTitle item.
            /// </summary>
            [RepositoryItem("8933de81-7251-45fc-ab99-c985b2ecf3b3")]
            public virtual Ranorex.Text DemoDrivenTitle
            {
                get
                {
                    return _demodriventitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DemoDrivenTitle item info.
            /// </summary>
            [RepositoryItemInfo("8933de81-7251-45fc-ab99-c985b2ecf3b3")]
            public virtual RepoItemInfo DemoDrivenTitleInfo
            {
                get
                {
                    return _demodriventitleInfo;
                }
            }

            /// <summary>
            /// The GroupActivityV3 item.
            /// </summary>
            [RepositoryItem("94eb7b91-1abe-43a2-bd03-14066965967c")]
            public virtual Ranorex.Form GroupActivityV3
            {
                get
                {
                    return _groupactivityv3Info.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The GroupActivityV3 item info.
            /// </summary>
            [RepositoryItemInfo("94eb7b91-1abe-43a2-bd03-14066965967c")]
            public virtual RepoItemInfo GroupActivityV3Info
            {
                get
                {
                    return _groupactivityv3Info;
                }
            }

            /// <summary>
            /// The AddGroup item.
            /// </summary>
            [RepositoryItem("215f1f0f-a7cd-409f-b4f0-f3d3caa20554")]
            public virtual Ranorex.Button AddGroup
            {
                get
                {
                    return _addgroupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddGroup item info.
            /// </summary>
            [RepositoryItemInfo("215f1f0f-a7cd-409f-b4f0-f3d3caa20554")]
            public virtual RepoItemInfo AddGroupInfo
            {
                get
                {
                    return _addgroupInfo;
                }
            }

            /// <summary>
            /// The GroupEntry item.
            /// </summary>
            [RepositoryItem("6631966a-ee17-4f57-869c-7292393020ca")]
            public virtual Ranorex.Text GroupEntry
            {
                get
                {
                    return _groupentryInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroupEntry item info.
            /// </summary>
            [RepositoryItemInfo("6631966a-ee17-4f57-869c-7292393020ca")]
            public virtual RepoItemInfo GroupEntryInfo
            {
                get
                {
                    return _groupentryInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
