///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AndroidKeePassSample.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntryByUsercodeAction recording.
    /// </summary>
    [TestModule("02aa671f-201d-4994-9f21-8ee7e41ed204", ModuleType.Recording, 1)]
    public partial class AddEntryByUsercodeAction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AndroidKeePassSample.AndroidKeePassSampleRepository repository.
        /// </summary>
        public static global::AndroidKeePassSample.AndroidKeePassSampleRepository repo = global::AndroidKeePassSample.AndroidKeePassSampleRepository.Instance;

        static AddEntryByUsercodeAction instance = new AddEntryByUsercodeAction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntryByUsercodeAction()
        {
            varTitle = "WordPressDemo";
            varUsername = "admin";
            varURL = "http://bitly.com/wp_demo";
            varPassword = "demo123";
            varIconIndex = "5";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntryByUsercodeAction Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsername;

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("1899110a-905e-420e-9f1b-12d6dd6885c3")]
        public string varUsername
        {
            get { return _varUsername; }
            set { _varUsername = value; }
        }

        string _varURL;

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("554a2393-2968-4679-a78a-9627e27649ad")]
        public string varURL
        {
            get { return _varURL; }
            set { _varURL = value; }
        }

        string _varPassword;

        /// <summary>
        /// Gets or sets the value of variable varPassword.
        /// </summary>
        [TestVariable("25796c23-99eb-47a2-8f89-0bbf0797a7ce")]
        public string varPassword
        {
            get { return _varPassword; }
            set { _varPassword = value; }
        }

        string _varIconIndex;

        /// <summary>
        /// Gets or sets the value of variable varIconIndex.
        /// </summary>
        [TestVariable("18d2ff01-592a-486d-abcd-09e93af66cac")]
        public string varIconIndex
        {
            get { return _varIconIndex; }
            set { _varIconIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varIconIndexRepo.
        /// </summary>
        [TestVariable("bb6715bb-f398-4464-b5bd-2861dffd62af")]
        public string varIconIndexRepo
        {
            get { return repo.varIconIndexRepo; }
            set { repo.varIconIndexRepo = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("da583ac7-9ed2-4def-a86e-48a0d0839bff")]
        public string varTitle
        {
            get { return repo.varTitle; }
            set { repo.varTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GroupActivity.Internet' at Center", repo.ComAndroidKeepass.GroupActivity.InternetInfo, new RecordItemIndex(0));
            repo.ComAndroidKeepass.GroupActivity.Internet.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GroupActivity.AddEntry' at Center", repo.ComAndroidKeepass.GroupActivity.AddEntryInfo, new RecordItemIndex(1));
            repo.ComAndroidKeepass.GroupActivity.AddEntry.Touch();
            Delay.Milliseconds(500);
            
            AddEntryWithParams(varTitle, varUsername, varPassword, varURL, varIconIndex);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.Save' at Center", repo.ComAndroidKeepass.EntryActivity.SaveInfo, new RecordItemIndex(3));
            repo.ComAndroidKeepass.EntryActivity.Save.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
