///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AndroidKeePassSample.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntry recording.
    /// </summary>
    [TestModule("d048dbe1-dde0-4578-b465-c15c9bedf535", ModuleType.Recording, 1)]
    public partial class AddEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AndroidKeePassSample.AndroidKeePassSampleRepository repository.
        /// </summary>
        public static global::AndroidKeePassSample.AndroidKeePassSampleRepository repo = global::AndroidKeePassSample.AndroidKeePassSampleRepository.Instance;

        static AddEntry instance = new AddEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntry()
        {
            varTitle = "WordPressDemo";
            varUsername = "admin";
            varURL = "http://bitly.com/wp_demo";
            varPassword = "demo123";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsername;

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("0be7f0a4-652e-4992-bbd4-5dd6690e9b5a")]
        public string varUsername
        {
            get { return _varUsername; }
            set { _varUsername = value; }
        }

        string _varURL;

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("eefd626a-78fa-45f1-9a9f-c55cf90223eb")]
        public string varURL
        {
            get { return _varURL; }
            set { _varURL = value; }
        }

        string _varPassword;

        /// <summary>
        /// Gets or sets the value of variable varPassword.
        /// </summary>
        [TestVariable("c6a511e9-6172-44bf-8181-caa1725043e6")]
        public string varPassword
        {
            get { return _varPassword; }
            set { _varPassword = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varIconIndexRepo.
        /// </summary>
        [TestVariable("bb6715bb-f398-4464-b5bd-2861dffd62af")]
        public string varIconIndexRepo
        {
            get { return repo.varIconIndexRepo; }
            set { repo.varIconIndexRepo = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("7ca07e60-36d3-44e0-8980-0b0aef933ddf")]
        public string varTitle
        {
            get { return repo.varTitle; }
            set { repo.varTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GroupActivity.Internet' at Center", repo.ComAndroidKeepass.GroupActivity.InternetInfo, new RecordItemIndex(0));
            repo.ComAndroidKeepass.GroupActivity.Internet.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GroupActivity.AddEntry' at Center", repo.ComAndroidKeepass.GroupActivity.AddEntryInfo, new RecordItemIndex(1));
            repo.ComAndroidKeepass.GroupActivity.AddEntry.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.TextFields.EntryTitle' at Center", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryTitleInfo, new RecordItemIndex(2));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryTitle.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varTitle' on item 'ComAndroidKeepass.EntryActivity.TextFields.EntryTitle'.", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryTitleInfo, new RecordItemIndex(3));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryTitle.Element.SetAttributeValue("Text", varTitle);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.IconButton' at Center", repo.ComAndroidKeepass.EntryActivity.IconButtonInfo, new RecordItemIndex(4));
            repo.ComAndroidKeepass.EntryActivity.IconButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.IconImage' at Center", repo.ComAndroidKeepass.IconImageInfo, new RecordItemIndex(5));
            repo.ComAndroidKeepass.IconImage.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.TextFields.EntryUserName' at Center", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUserNameInfo, new RecordItemIndex(6));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUserName.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varUsername' on item 'ComAndroidKeepass.EntryActivity.TextFields.EntryUserName'.", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUserNameInfo, new RecordItemIndex(7));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUserName.Element.SetAttributeValue("Text", varUsername);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.TextFields.EntryUrl' at Center", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUrlInfo, new RecordItemIndex(8));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUrl.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varURL' on item 'ComAndroidKeepass.EntryActivity.TextFields.EntryUrl'.", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUrlInfo, new RecordItemIndex(9));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryUrl.Element.SetAttributeValue("Text", varURL);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.TextFields.EntryPassword' at Center", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryPasswordInfo, new RecordItemIndex(10));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryPassword.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varPassword' on item 'ComAndroidKeepass.EntryActivity.TextFields.EntryPassword'.", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryPasswordInfo, new RecordItemIndex(11));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryPassword.Element.SetAttributeValue("Text", varPassword);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.TextFields.EntryConfpassword' at Center", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryConfpasswordInfo, new RecordItemIndex(12));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryConfpassword.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varPassword' on item 'ComAndroidKeepass.EntryActivity.TextFields.EntryConfpassword'.", repo.ComAndroidKeepass.EntryActivity.TextFields.EntryConfpasswordInfo, new RecordItemIndex(13));
            repo.ComAndroidKeepass.EntryActivity.TextFields.EntryConfpassword.Element.SetAttributeValue("Text", varPassword);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.EntryActivity.Save' at Center", repo.ComAndroidKeepass.EntryActivity.SaveInfo, new RecordItemIndex(14));
            repo.ComAndroidKeepass.EntryActivity.Save.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
