///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AndroidKeePassSample.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddCategory recording.
    /// </summary>
    [TestModule("5f7a07e0-8f71-497c-80ab-4a2beff35e17", ModuleType.Recording, 1)]
    public partial class AddGroup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AndroidKeePassSample.AndroidKeePassSampleRepository repository.
        /// </summary>
        public static global::AndroidKeePassSample.AndroidKeePassSampleRepository repo = global::AndroidKeePassSample.AndroidKeePassSampleRepository.Instance;

        static AddGroup instance = new AddGroup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddGroup()
        {
            varGroupName = "Ranorex";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddGroup Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varGroupName.
        /// </summary>
        [TestVariable("700be616-289f-4ecd-ae55-e4c1db9eb018")]
        public string varGroupName
        {
            get { return repo.varGroupName; }
            set { repo.varGroupName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.GroupActivity.AddGroup' at Center", repo.ComAndroidKeepass.GroupActivity.AddGroupInfo, new RecordItemIndex(0));
            repo.ComAndroidKeepass.GroupActivity.AddGroup.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varGroupName' on item 'ComAndroidKeepass.GroupName'.", repo.ComAndroidKeepass.GroupNameInfo, new RecordItemIndex(1));
            repo.ComAndroidKeepass.GroupName.Element.SetAttributeValue("Text", varGroupName);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'ComAndroidKeepass'.", repo.ComAndroidKeepass.SelfInfo, new RecordItemIndex(2));
            repo.ComAndroidKeepass.Self.PressKeys("{ENTER}");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'ComAndroidKeepass'.", repo.ComAndroidKeepass.SelfInfo, new RecordItemIndex(3));
            repo.ComAndroidKeepass.Self.PressKeys("{ENTER}");
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
