///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AndroidKeePassSample.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeployApp recording.
    /// </summary>
    [TestModule("71b73178-eb88-4715-8716-32516ac045b2", ModuleType.Recording, 1)]
    public partial class DeployApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AndroidKeePassSample.AndroidKeePassSampleRepository repository.
        /// </summary>
        public static global::AndroidKeePassSample.AndroidKeePassSampleRepository repo = global::AndroidKeePassSample.AndroidKeePassSampleRepository.Instance;

        static DeployApp instance = new DeployApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeployApp()
        {
            varDeviceName = "Android Device";
            varAPKFilePath = "KeePassDroid.apk";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeployApp Instance
        {
            get { return instance; }
        }

#region Variables

        string _varDeviceName;

        /// <summary>
        /// Gets or sets the value of variable varDeviceName.
        /// </summary>
        [TestVariable("27130376-bd8a-47a9-b9bc-44c3f6a85001")]
        public string varDeviceName
        {
            get { return _varDeviceName; }
            set { _varDeviceName = value; }
        }

        string _varAPKFilePath;

        /// <summary>
        /// Gets or sets the value of variable varAPKFilePath.
        /// </summary>
        [TestVariable("cc0c6878-e967-47f0-abdb-32d3154a1ccd")]
        public string varAPKFilePath
        {
            get { return _varAPKFilePath; }
            set { _varAPKFilePath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "User", varAPKFilePath, new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "User", varDeviceName, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Application", "Deploying android app from variable '$varAPKFilePath'  to device from variable '$varDeviceName'.", new RecordItemIndex(2));
            Host.Local.InstrumentAndDeployAndroidApp(varDeviceName, varAPKFilePath, true, Host.DeploymentModes.Auto, 600000, new Ranorex.Core.Remoting.RecordItems.InstrumentApkOptions() { AutoSettingsAdjustment = true, AvoidResourcesDecompiling = true, StaticInstrumentation = false, MultidexApplication = false, RedistributedSmali = false, DebugInformation = false, InstrumentationFlags = "", EnableWebTesting = true, TreeSimplification = true, FullImageComparison = false, ExtractNativeLibs = false, SetTestOnlyFalse = true, RIdClass = "", KeyStore = "", KeyAlias = "", JdkBinPath = "", KeyStorePass = "", KeyPass = "", SkipInstrumentation = false, SkipDeployment = false, ResignOnly = false });
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
