///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AndroidKeePassSample.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RunApp recording.
    /// </summary>
    [TestModule("160b2cac-1f7f-415a-80af-438b6ea9ccf7", ModuleType.Recording, 1)]
    public partial class RunApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AndroidKeePassSample.AndroidKeePassSampleRepository repository.
        /// </summary>
        public static global::AndroidKeePassSample.AndroidKeePassSampleRepository repo = global::AndroidKeePassSample.AndroidKeePassSampleRepository.Instance;

        static RunApp instance = new RunApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RunApp()
        {
            varDeviceName = "Android Device";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RunApp Instance
        {
            get { return instance; }
        }

#region Variables

        string _varDeviceName;

        /// <summary>
        /// Gets or sets the value of variable varDeviceName.
        /// </summary>
        [TestVariable("b07de26f-29ed-4c80-b141-170164ede259")]
        public string varDeviceName
        {
            get { return _varDeviceName; }
            set { _varDeviceName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.android.keepass' on device from variable $varDeviceName.", new RecordItemIndex(0));
            Host.Local.RunMobileApp(varDeviceName, "com.android.keepass", true);
            Delay.Milliseconds(3500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
