///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AndroidKeePassSample.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateCategory recording.
    /// </summary>
    [TestModule("c9012a01-70b1-41b7-bb36-3ed0d079c8a3", ModuleType.Recording, 1)]
    public partial class ValidateGroup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AndroidKeePassSample.AndroidKeePassSampleRepository repository.
        /// </summary>
        public static global::AndroidKeePassSample.AndroidKeePassSampleRepository repo = global::AndroidKeePassSample.AndroidKeePassSampleRepository.Instance;

        static ValidateGroup instance = new ValidateGroup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateGroup()
        {
            varGroupName = "Ranorex";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateGroup Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varGroupName.
        /// </summary>
        [TestVariable("713af05f-d45d-4d1c-b03d-333542bccfa7")]
        public string varGroupName
        {
            get { return repo.varGroupName; }
            set { repo.varGroupName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varGroupName) on item 'ComAndroidKeepass.GroupActivity.GroupEntry'.", repo.ComAndroidKeepass.GroupActivity.GroupEntryInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ComAndroidKeepass.GroupActivity.GroupEntryInfo, "Text", varGroupName);
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
